### ISSUE TITLE
pp. 195訳注, 311 出典の明示と参考文献への追加

### ISSUE THREAD

**Issue by sumim** [ohmsha/test-driven-development-ja#4]
- 変更前

    > この逸話は

- 変更後

    > この逸話[Ka96 p.533]は

    もしくは、余白が許さない場合、あるいは表記の統一を優先する場合は

    > この逸話[Ka96]は

- 参考文献リスト（p. 311付近）に追加

    [Ka96] (p. 195)
    Kay, A. C. 1996. "The Early History of Smalltalk", History of Programming Languages II.  ACM Press/Addison-Wesley Publishing Co. New York, pp. 511-598. http://www.vpri.org/pdf/hc_smalltalk_history.pdf

もし参考文献リストが和田さんの厳選書集の意味合いが強く、通常の出典明示の目的のための文献追加によりその調和を乱してしまう場合は、件の脚注の「（この逸話は～）」部分の「（Kay, A. C. 1996. "The Early History of Smalltalk"）」等への置き換えなどでご対応いただければ幸いです。

**Comment by hisashim** [comment]
@sumim どうもありがとうございます。第2刷での修正候補にさせていただきます。
（改ページ位置の具合にもよりますが、参考文献に追加して、本文では
[Ka96]で参照する形になるかと思います。）

**Comment by hisashim** [comment]
第2刷で修正されているはずですので、閉じます。
ご指摘ありがとうございます。
