### ISSUE TITLE
p. 239 「integer」は訳してしまってよいような…、bitAt:put: の引数の誤りを訂正（原著から）

### ISSUE THREAD

**Issue by sumim** [ohmsha/test-driven-development-ja#6]
- 変更前
    > integerの振る舞いに

    > integerはオブジェクトの

- 変更後
    > 整数の振る舞いに

    > 整数はオブジェクトの

前者の原文は I remember puzzling over integers when I was first learning Smalltalk. と小文字スタートでかつ複数形なので（値の型やクラスのインスタンスではなく）一般的な「整数」（あるいは「整数値」）を指していると思います。後者は文頭なので「Integers are really values masquerading as objects.」と大文字になっていますが、やはり同じニュアンスかと。

関連して、p. 269 の「Smalltalkの整数型は～本当に整数として振る舞う」の「Smalltalk integers act like integers」にある「integers」も同じ表現なので、「型」よりは「値」の方がしっくりくるように思います。

- 変更前
    > 2ビット目を1に変えたのに

    > a := a bitAt: 2 put: 1.

- 変更後
    > 3ビット目を1に変えたのに

    > a := a bitAt: 3 put: 1.

原著から間違っています。前者の「ビット目」については、0ビット目から数えると間違いではないのですが、断りなしにそうした表現はあまりしないように思います（原文は If I change bit 2 to a 1, なので微妙です）。後者のコードの方は完全に間違いで、Smalltalkは1オリジン（one-based）なので、3番目のビットを1に変えないと6を返しません。

**Comment by hisashim** [comment]
@sumim ありがとうございます。編集時に見落としていました。
こんな感じでしょうか。

p. 239, 第1段落、コードブロック、第2段落:
```diff
-私がSmalltalkを学び始めたとき、integerの振る舞いに困惑したことを覚えている。
+私がSmalltalkを学び始めたとき、整数の振る舞いに困惑したことを覚えている。
 ...
-2ビット目を1に変えたのに、なぜ6に変わらず2のままのものがいるのだろう。
+3ビット目を1に変えたのに、なぜ6に変わらず2のままのものがいるのだろう。
 ...
-a := a bitAt: 2 put: 1.
+a := a bitAt: 3 put: 1.
...
-実はSmalltalkにおけるintegerはオブジェクトのふりをした値だ。
+実はSmalltalkにおける整数はオブジェクトのふりをした値だ。
```

p. 269, 第4段落:
```diff
-例えばSmalltalkの整数型は32ビットのカウンタではなく本当に整数として振る舞うので、
+例えばSmalltalkの整数値は32ビットのカウンタではなく本当に整数として振る舞うので、
 ...
-もちろんその整数型にも実際には最大値はあるが
+もちろんその整数にも実際には最大値はあるが
```

**Comment by sumim** [comment]
はい。そのような感じです。

**Comment by hisashim** [comment]
@sumim ありがとうございます。第2刷で反映します。

**Comment by hisashim** [comment]
第2刷で修正されているはずですので、閉じます。
ご指摘ありがとうございます。
