### ISSUE TITLE
p. 270 TriangleTest コードの最後の ^sides asSet size が抜けています

### ISSUE THREAD

**Issue by sumim** [ohmsha/test-driven-development-ja#7]
t/o

**Comment by hisashim** [comment]
@sumim ご指摘ありがとうございます。
原文から日本語版に転記した際の編集ミスでした。恐縮です。

p. 270, SmalltalkによるTriangleTestの例の最終行「^sides asSet size」が
欠落している。

```diff
    sides first &lt;= 0 ifTrue: [self fail].
    (sides at: 1) + (sides at: 2) &lt;= (sides at: 3) ifTrue: [self fail].
+   ^sides asSet size
```

第1刷で確認しました。第2刷に反映します。

**Comment by hisashim** [comment]
改ページ位置の都合で、次のように変更することになりました
（コードブロック全体をやや縮小し、p. 271からp. 270へ本文を2行移動）。

pp. 270-271, SmalltalkによるTriangleTestの例の最終行「^sides asSet size」が
欠落している。

  * 変更前:

    p. 270:
    > ```
    >   sides first &lt;= 0 ifTrue: [self fail].
    >   (sides at: 1) + (sides at: 2) &lt;= (sides at: 3) ifTrue: [self fail].
    > ```
    > どのようなときにテストを消すべきか
    > ...

    p. 271:
    > つまり、もし2つのテストに自信の面でもコミュニケーションの面でも
    > 重複があるのであれば、役に立たないほうを消そう。

  * 変更後:

    p. 270:
    > ```
    >   sides first &lt;= 0 ifTrue: [self fail].
    >   (sides at: 1) + (sides at: 2) &lt;= (sides at: 3) ifTrue: [self fail].
    >   ^sides asSet size
    > ```
    > どのようなときにテストを消すべきか
    > ...
    > つまり、もし2つのテストに自信の面でもコミュニケーションの面でも
    > 重複があるのであれば、役に立たないほうを消そう。

    p. 271:
    （最初の2行を前ページへ移動）

**Comment by sumim** [comment]
恐縮です。プロダクトコードの一番大事な行なので復活してもらえるのはありがたいです。

**Comment by hisashim** [comment]
知識も余裕もなくて、気がついていませんでした。すみません。
ご指摘いただきありがとうございます。

第2刷で修正されているはずですので、閉じます。
