### ISSUE TITLE
P.105 JUnit4で assertEquals(new Object[]... がテストをパスする

### ISSUE THREAD

**Issue by tomoki1207** [ohmsha/test-driven-development-ja#8]
下記環境で勉強していたところ、テストを失敗すべきところでパスしてしまいました。
Java: JRE1.8.0_151
JUnit: 4.12.0

[assertArrayEquals(Object[] expecteds, Object[] actuals)](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/Assert.java#L299-L301) でオーバーロードされているせいかもしれません。

77行目でエラーが出ず、78行目でエラーが検出されます。
![errrortrace](https://user-images.githubusercontent.com/3643499/32255349-87fea3de-beea-11e7-8125-434509be2709.png)

**Comment by twada** [comment]
@tomoki1207 ご報告ありがとうございます！

『テスト駆動開発』の第I部は JUnit5 で進めたのですが、
`assertEquals(Object[] expecteds, Object[] actuals)`
の挙動が JUnit3, JUnit4, JUnit5 でそれぞれ異なるようです。

当該のテストは JUnit3 と JUnit5 では（予想通り正しく）失敗し、JUnit4 では仰るとおり `assertArrayEquals(Object[] expecteds, Object[] actuals)` へバイパスされるので通ってしまうようです。
（`assertArrayEquals` は JUnit4 の最新版で deprecated 扱いになり, JUnit5 では削除されています）

書籍を JUnit5 で進めていたので、これは盲点でした。

これからは JUnit5 の時代になるのでコードはこのままにしておくかどうか迷うところですが（増刷時に判断します）、少なくとも JUnit4 向けの訳注は入れたいと思います。

この度はご報告ありがとうございました。
また何かありましたら、お気軽にご報告いただけますと幸いです。

**Comment by twada** [comment]
あるいは、仰るとおり `assertTrue` に寄せてしまった方が曖昧さがなくなるかもしれませんね。
少なくとも何かの形で修正はさせていただきます。ありがとうございます。

**Comment by twada** [comment]
@tomoki1207 第3刷が出ることになりましたので、増刷の際に p.105 のご指摘のあった箇所を `assertTrue` を使うように変更いたしました。改めまして、この度はご報告誠にありがとうございました。
