### ISSUE TITLE
iOSのiBooksでの目次表示が変

### ISSUE THREAD

**Issue by yuyabu** [ohmsha/test-driven-development-ja#9]
不自然なスペースが表示されています

iPhoneとiPadで確認済み

![img_2840](https://user-images.githubusercontent.com/23971274/34431485-fb6a78e8-ecb2-11e7-8b31-1e0538e6d1ea.PNG)

オーム社さんの他の本(達人プログラマー)では自然に表示されています。
![img_2842](https://user-images.githubusercontent.com/23971274/34431520-46a8dfe8-ecb3-11e7-896e-9c28e2180376.PNG)

iBOOKS 4.15
iOS 11.2.1

**Comment by hisashim** [comment]
丁寧なご指摘どうもありがとうございます。

調べたところ、目次項目を作るときに前後に不要な空白や改行が残っており、
iBooksではそれが描画されていたようです。確認が行き届かず申し訳ありません。

第3刷での問題として、対策を施しておきます。

**Comment by hisashim** [comment]
ご報告が遅くなりましたが、おかげさまで、近日発行の第4刷で反映されるかと思います。
詳細なご指摘ありがとうございました。
